export const partyCategories = {
  core: {
    title: "ליבה",
    parameters: [
      { id: "type", label: "סוג מפלגה", options: ["חרדים", "ערבים", "חילוניים", "מעורב"] },
      { id: "security", label: "ביטחון", options: ["ימין", "מרכז", "שמאל"] },
      { id: "economy", label: "יוקר המחיה / דיור", options: ["קפיטליסט", "סוציאליסט", "מעורב"] },
      { id: "harediGov", label: "שילוב חרדים בממשלה", options: ["כן", "לא", "חלקי"] },
      { id: "arabGov", label: "שילוב ערבים בממשלה", options: ["כן", "לא", "חלקי"] },
      { id: "governance", label: "משילות או דמוקרטיה", options: ["משילות", "דמוקרטיה", "איזון"] },
    ],
  },
  daily: {
    title: "יומיום",
    parameters: [
      { id: "shabbatTransport", label: "תחבורה בשבת", options: ["בעד", "נגד", "מקומי"] },
      { id: "civilMarriage", label: "נישואין אזרחיים", options: ["בעד", "נגד", "חלקי"] },
      { id: "equalBurden", label: "שוויון בנטל", options: ["בעד", "נגד", "חלקי"] },
      { id: "eduSubsidy", label: "סבסוד השכלה גבוהה", options: ["בעד", "נגד", "חלקי"] },
      { id: "eduFrom0", label: "חינוך מגיל 0", options: ["בעד", "נגד", "חלקי"] },
      { id: "climate", label: "משבר אקלים", options: ["עדיפות גבוהה", "עדיפות נמוכה", "לא בסדר יום"] },
      { id: "eduChoice", label: "חופש בחירה בחינוך", options: ["בעד", "נגד", "חלקי"] },
      { id: "reservists", label: "הטבות למילואימניקים", options: ["בעד", "נגד", "חלקי"] },
      { id: "legalization", label: "לגליזציה", options: ["בעד", "נגד", "דקרימינליזציה"] },
    ],
  },
}

export const leaderParameters = [
  { id: "securityBg", label: "רקע ביטחוני", type: "rating" },
  { id: "economicBg", label: "רקע כלכלי", type: "rating" },
  { id: "pressure", label: "יכולת עמידה בלחצים", type: "rating" },
  { id: "brokenPromises", label: "הפרת הבטחות ליבה", type: "rating" },
  { id: "consistency", label: "עקביות", type: "rating" },
  { id: "authority", label: "סמכותיות", type: "scale" },
  { id: "communication", label: "אנגלית ותקשורת", type: "rating" },
  { id: "worldRelations", label: "יחסים עם מנהיגי עולם", type: "rating" },
  { id: "criminal", label: "חשדות ופלילים", type: "status" },
  { id: "lifestyle", label: "סגנון חיים", type: "text" },
]

// Sample party data - can be expanded
export const parties = [
  {
    id: "likud",
    name: "הליכוד",
    leader: "בנימין נתניהו",
    color: "#0066cc",
    values: {
      type: "מעורב",
      security: "ימין",
      economy: "קפיטליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "משילות",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "חלקי",
      eduFrom0: "חלקי",
      climate: "עדיפות נמוכה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "נגד",
    },
  },
  {
    id: "yeshAtid",
    name: "יש עתיד",
    leader: "יאיר לפיד",
    color: "#00a0dc",
    values: {
      type: "חילוניים",
      security: "מרכז",
      economy: "מעורב",
      harediGov: "לא",
      arabGov: "חלקי",
      governance: "דמוקרטיה",
      shabbatTransport: "בעד",
      civilMarriage: "בעד",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "דקרימינליזציה",
    },
  },
  {
    id: "mahaneLevi",
    name: "המחנה הממלכתי",
    leader: "בני גנץ",
    color: "#1e3a5f",
    values: {
      type: "מעורב",
      security: "מרכז",
      economy: "מעורב",
      harediGov: "חלקי",
      arabGov: "חלקי",
      governance: "איזון",
      shabbatTransport: "מקומי",
      civilMarriage: "חלקי",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "דקרימינליזציה",
    },
  },
  {
    id: "shas",
    name: "ש״ס",
    leader: "אריה דרעי",
    color: "#006400",
    values: {
      type: "חרדים",
      security: "ימין",
      economy: "סוציאליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "משילות",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "בעד",
      eduFrom0: "חלקי",
      climate: "לא בסדר יום",
      eduChoice: "בעד",
      reservists: "חלקי",
      legalization: "נגד",
    },
  },
  {
    id: "avoda",
    name: "העבודה",
    leader: "יאיר גולן",
    color: "#e30613",
    values: {
      type: "חילוניים",
      security: "שמאל",
      economy: "סוציאליסט",
      harediGov: "חלקי",
      arabGov: "כן",
      governance: "דמוקרטיה",
      shabbatTransport: "בעד",
      civilMarriage: "בעד",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "בעד",
    },
  },
  {
    id: "yahadut",
    name: "יהדות התורה",
    leader: "יצחק גולדקנופף",
    color: "#000080",
    values: {
      type: "חרדים",
      security: "ימין",
      economy: "סוציאליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "משילות",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "בעד",
      eduFrom0: "נגד",
      climate: "לא בסדר יום",
      eduChoice: "בעד",
      reservists: "חלקי",
      legalization: "נגד",
    },
  },
]

export const leaders = [
  {
    id: "netanyahu",
    name: "בנימין נתניהו",
    party: "הליכוד",
    image: "/leaders/netanyahu.jpg",
    color: "#0066cc",
    values: {
      securityBg: 3,
      economicBg: 4,
      pressure: 5,
      brokenPromises: 4,
      consistency: 2,
      authority: 5,
      communication: 5,
      worldRelations: 4,
      criminal: "כתבי אישום פעילים",
      lifestyle: "יוקרתי",
    },
  },
  {
    id: "lapid",
    name: "יאיר לפיד",
    party: "יש עתיד",
    image: "/leaders/lapid.jpg",
    color: "#00a0dc",
    values: {
      securityBg: 1,
      economicBg: 2,
      pressure: 3,
      brokenPromises: 3,
      consistency: 3,
      authority: 2,
      communication: 5,
      worldRelations: 4,
      criminal: "ללא",
      lifestyle: "בינוני-גבוה",
    },
  },
  {
    id: "gantz",
    name: "בני גנץ",
    party: "המחנה הממלכתי",
    image: "/leaders/gantz.jpg",
    color: "#1e3a5f",
    values: {
      securityBg: 5,
      economicBg: 2,
      pressure: 4,
      brokenPromises: 3,
      consistency: 3,
      authority: 3,
      communication: 3,
      worldRelations: 3,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
  {
    id: "deri",
    name: "אריה דרעי",
    party: "ש״ס",
    image: "/leaders/deri.jpg",
    color: "#006400",
    values: {
      securityBg: 1,
      economicBg: 3,
      pressure: 4,
      brokenPromises: 4,
      consistency: 4,
      authority: 4,
      communication: 3,
      worldRelations: 2,
      criminal: "הרשעות קודמות",
      lifestyle: "יוקרתי",
    },
  },
  {
    id: "golan",
    name: "יאיר גולן",
    party: "העבודה",
    image: "/leaders/golan.jpg",
    color: "#e30613",
    values: {
      securityBg: 5,
      economicBg: 2,
      pressure: 4,
      brokenPromises: 1,
      consistency: 4,
      authority: 3,
      communication: 4,
      worldRelations: 3,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
  {
    id: "goldknopf",
    name: "יצחק גולדקנופף",
    party: "יהדות התורה",
    image: "/leaders/goldknopf.jpg",
    color: "#000080",
    values: {
      securityBg: 1,
      economicBg: 2,
      pressure: 3,
      brokenPromises: 2,
      consistency: 4,
      authority: 3,
      communication: 2,
      worldRelations: 1,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
]
