/** מאפיינים מבניים/קואליציוניים — לא עמדות מדיניות יומיומיות */
export const partyCategories = {
  attributes: {
    title: "מאפייני המפלגה",
    parameters: [
      {
        id: "type",
        label: "סוג מפלגה",
        options: ["חרדים", "ערבים", "חילוניים", "מעורב"],
      },
      {
        id: "security",
        label: "גישה ביטחונית",
        options: ["ימין", "מרכז", "שמאל"],
      },
      {
        id: "economy",
        label: "גישה כלכלית",
        options: ["קפיטליסט", "סוציאליסט", "מעורב"],
      },
      {
        id: "harediGov",
        label: "שילוב חרדים בממשלה",
        options: ["כן", "לא", "חלקי"],
      },
      {
        id: "arabGov",
        label: "שילוב ערבים בממשלה",
        options: ["כן", "לא", "חלקי"],
      },
    ],
  },
  issues: {
    title: "עמדות בנושאים ספציפיים",
    parameters: [
      {
        id: "governance",
        label: "הרפורמה המשפטית",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "shabbatTransport",
        label: "תחבורה בשבת",
        options: ["בעד", "נגד", "מקומי"],
      },
      {
        id: "civilMarriage",
        label: "נישואין אזרחיים",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "equalBurden",
        label: "שוויון בנטל",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "eduSubsidy",
        label: "סבסוד השכלה גבוהה",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "eduFrom0",
        label: "חינוך מגיל 0",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "climate",
        label: "משבר אקלים",
        options: ["עדיפות גבוהה", "עדיפות נמוכה", "לא בסדר יום"],
      },
      {
        id: "eduChoice",
        label: "חופש בחירה בחינוך",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "reservists",
        label: "הטבות למילואימניקים",
        options: ["בעד", "נגד", "חלקי"],
      },
      {
        id: "legalization",
        label: "לגליזציה",
        options: ["בעד", "נגד", "דקרימינליזציה"],
      },
    ],
  },
} as const;

export const allPartyComparisonParameters = [
  ...partyCategories.attributes.parameters,
  ...partyCategories.issues.parameters,
] as const;

export const leaderParameters = [
  { id: "securityBg", label: "רקע ביטחוני", type: "rating" },
  { id: "economicBg", label: "רקע כלכלי", type: "rating" },
  { id: "pressure", label: "יכולת עמידה בלחצים", type: "rating" },
  { id: "brokenPromises", label: "הפרת הבטחות ליבה", type: "rating" },
  { id: "consistency", label: "עקביות", type: "rating" },
  { id: "authority", label: "סמכותיות", type: "scale" },
  { id: "communication", label: "אנגלית ותקשורת", type: "rating" },
  { id: "worldRelations", label: "יחסים עם מנהיגי עולם", type: "rating" },
  { id: "criminal", label: "חשדות ופלילים", type: "status" },
  { id: "lifestyle", label: "סגנון חיים", type: "text" },
];

// Sample party data - can be expanded
export const parties = [
  {
    id: "likud",
    name: "הליכוד",
    leader: "בנימין נתניהו",
    color: "#0066cc",
    mandates: 26,
    image: "/parties/likud.png",
    members: ["ישראל כץ", "ניר ברקת", "יריב לוין", "מירי רגב", "יואב גלנט"],
    vision:
      "החזון: ישראל כמעצמה חזקה, חופשית ובטוחה.\n\n" +
      "המפלגה שואפת שבעוד 10 שנים ישראל תהיה המדינה הכי חזקה במזרח התיכון בזכות צבא חזק וכלכלה של שוק חופשי (פחות התערבות של הממשלה, יותר תחרות). הליכוד דוגל בשמירה על ארץ ישראל ועל ריבונות יהודית, בלי להקים מדינה פלסטינית, מתוך אמונה שרק כוח והרתעה יביאו שלום אמת וביטחון.",
    values: {
      type: "מעורב",
      security: "ימין",
      economy: "קפיטליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "בעד",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "חלקי",
      eduFrom0: "חלקי",
      climate: "עדיפות נמוכה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "נגד",
    },
  },
  {
    id: "yeshAtid",
    name: "יש עתיד",
    leader: "יאיר לפיד",
    color: "#00a0dc",
    mandates: 24,
    image: "/parties/yeshAtid.png",
    members: [
      "מאיר כהן",
      "קארין אלהרר",
      "רם בן ברק",
      "בועז טופורובסקי",
      "נעמה לזימי",
    ],
    vision:
      "החזון: ישראל כדמוקרטיה ליברלית, חילונית ומתקדמת.\n\n" +
      'המפלגה רוצה שבעוד עשור ישראל תהיה מדינה "נורמלית" ומודרנית, שבה יש שוויון בנטל (כולם מתגייסים או משרתים), הפרדה בין דת לפוליטיקה, ומערכת חינוך שמכינה את הצעירים לשוק העבודה העולמי. המטרה היא לשמור על ישראל יהודית ודמוקרטית דרך היפרדות מהפלסטינים וחיזוק המעמד של ישראל בעולם.',
    values: {
      type: "חילוניים",
      security: "מרכז",
      economy: "מעורב",
      harediGov: "לא",
      arabGov: "חלקי",
      governance: "נגד",
      shabbatTransport: "בעד",
      civilMarriage: "בעד",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "דקרימינליזציה",
    },
  },
  {
    id: "mahaneLevi",
    name: "המחנה הממלכתי",
    leader: "בני גנץ",
    color: "#1e3a5f",
    mandates: 20,
    image: "/parties/mahaneLevi.png",
    members: [
      "גדי איזנקוט",
      "חילי טרופר",
      "פנינה תמנו-שטה",
      "מיכאל בירנבאום",
      "עופר שלח",
    ],
    vision:
      "החזון: ישראל מאוחדת, יציבה וממלכתית.\n\n" +
      'המפלגה שמה דגש על ה"ביחד" הישראלי. החזון שלה לעשור הקרוב הוא לבנות מחדש את המוסדות של המדינה (המשטרה, בתי המשפט, הכנסת) כך שכולם יבטחו בהם שוב. הם שואפים לביטחון שמבוסס על הסכמות רחבות, חיזוק ההתיישבות בנקודות אסטרטגיות, וניהול המדינה בצורה רגועה שמרכזת את הרוב המתון בעם.',
    values: {
      type: "מעורב",
      security: "מרכז",
      economy: "מעורב",
      harediGov: "חלקי",
      arabGov: "חלקי",
      governance: "נגד",
      shabbatTransport: "מקומי",
      civilMarriage: "חלקי",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "דקרימינליזציה",
    },
  },
  {
    id: "shas",
    name: "ש״ס",
    leader: "אריה דרעי",
    color: "#006400",
    mandates: 11,
    image: "/parties/shas.png",
    members: [
      "משה ארבל",
      "יצחק כהן",
      "מיכאל מלכיאלי",
      "חיים ביטון",
      "יעקב מרגי",
    ],
    vision:
      "החזון: ישראל חברתית עם נשמה יהודית-ספרדית.\n\n" +
      "המפלגה רוצה שבעוד 10 שנים ישראל תהיה מדינה שדואגת קודם כל למי שאין לו – צדק חלוקתי שבו המשאבים הולכים לפריפריה ולשכבות החלשות. במקביל, המטרה היא לחזק את הזהות היהודית-מסורתית של המדינה ולתת מקום של כבוד למורשת של יהדות המזרח בכל תחומי החיים.",
    values: {
      type: "חרדים",
      security: "ימין",
      economy: "סוציאליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "בעד",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "בעד",
      eduFrom0: "חלקי",
      climate: "לא בסדר יום",
      eduChoice: "בעד",
      reservists: "חלקי",
      legalization: "נגד",
    },
  },
  {
    id: "avoda",
    name: "העבודה",
    leader: "יאיר גולן",
    color: "#e30613",
    mandates: 18,
    image: "/parties/avoda.png",
    members: [
      "נעמה לזימי",
      "גלעד קריב",
      "אפרת רייטן",
      "עמירם לוין",
      "אורן חזן",
    ],
    vision:
      "החזון: ישראל כמדינת רווחה דמוקרטית ורודפת שלום.\n\n" +
      "המפלגה שואפת לחזור לישראל של שוויון חברתי עמוק – שבה הממשלה דואגת לבריאות, דיור וחינוך איכותי לכולם. בעשור הקרוב הם רוצים לראות מהלך אקטיבי לסיום הסכסוך עם הפלסטינים (פתרון שתי המדינות) כדי להציל את הדמוקרטיה הישראלית, ולהפוך את ישראל למקום שבו זכויות אדם וזכויות עובדים הן הערך העליון.",
    values: {
      type: "חילוניים",
      security: "שמאל",
      economy: "סוציאליסט",
      harediGov: "חלקי",
      arabGov: "כן",
      governance: "נגד",
      shabbatTransport: "בעד",
      civilMarriage: "בעד",
      equalBurden: "בעד",
      eduSubsidy: "בעד",
      eduFrom0: "בעד",
      climate: "עדיפות גבוהה",
      eduChoice: "בעד",
      reservists: "בעד",
      legalization: "בעד",
    },
  },
  {
    id: "yahadut",
    name: "יהדות התורה",
    leader: "יצחק גולדקנופף",
    color: "#000080",
    mandates: 8,
    image: "/parties/yahadut.png",
    members: ["משה גפני", "מאיר פרוש", "יעקב אשר", "ישראל אייכלר", "אורי מקלב"],
    vision:
      "החזון: ישראל שבה התורה היא מרכז החיים והקיום.\n\n" +
      "המפלגה רוצה להבטיח שבעוד 10 שנים עולם הישיבות ימשיך לגדול ללא הפרעה. המטרה היא לשמור על הסטטוס-קוו בענייני דת (שבת, כשרות, נישואין), להגן על החינוך החרדי העצמאי, ולדאוג שלציבור החרדי יהיו פתרונות למגורים ולתעסוקה שמתאימים לאורח החיים הדתי המחמיר.",
    values: {
      type: "חרדים",
      security: "ימין",
      economy: "סוציאליסט",
      harediGov: "כן",
      arabGov: "לא",
      governance: "בעד",
      shabbatTransport: "נגד",
      civilMarriage: "נגד",
      equalBurden: "נגד",
      eduSubsidy: "בעד",
      eduFrom0: "נגד",
      climate: "לא בסדר יום",
      eduChoice: "בעד",
      reservists: "חלקי",
      legalization: "נגד",
    },
  },
];

export const leaders = [
  {
    id: "netanyahu",
    name: "בנימין נתניהו",
    party: "הליכוד",
    image: "/leaders/netanyahu.png",
    color: "#0066cc",
    values: {
      securityBg: 3,
      economicBg: 4,
      pressure: 5,
      brokenPromises: 4,
      consistency: 2,
      authority: 5,
      communication: 5,
      worldRelations: 4,
      criminal: "כתבי אישום פעילים",
      lifestyle: "יוקרתי",
    },
  },
  {
    id: "yair",
    name: "יאיר לפיד",
    party: "יש עתיד",
    image: "/leaders/yair.png",
    color: "#00a0dc",
    values: {
      securityBg: 1,
      economicBg: 2,
      pressure: 3,
      brokenPromises: 3,
      consistency: 3,
      authority: 2,
      communication: 5,
      worldRelations: 4,
      criminal: "ללא",
      lifestyle: "בינוני-גבוה",
    },
  },
  {
    id: "beni",
    name: "בני גנץ",
    party: "המחנה הממלכתי",
    image: "/leaders/beni.png",
    color: "#1e3a5f",
    values: {
      securityBg: 5,
      economicBg: 2,
      pressure: 4,
      brokenPromises: 3,
      consistency: 3,
      authority: 3,
      communication: 3,
      worldRelations: 3,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
  {
    id: "arie",
    name: "אריה דרעי",
    party: "ש״ס",
    image: "/leaders/arie.png",
    color: "#006400",
    values: {
      securityBg: 1,
      economicBg: 3,
      pressure: 4,
      brokenPromises: 4,
      consistency: 4,
      authority: 4,
      communication: 3,
      worldRelations: 2,
      criminal: "הרשעות קודמות",
      lifestyle: "יוקרתי",
    },
  },
  {
    id: "golan",
    name: "יאיר גולן",
    party: "העבודה",
    image: "/leaders/golan.png",
    color: "#e30613",
    values: {
      securityBg: 5,
      economicBg: 2,
      pressure: 4,
      brokenPromises: 1,
      consistency: 4,
      authority: 3,
      communication: 4,
      worldRelations: 3,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
  {
    id: "itshak",
    name: "יצחק גולדקנופף",
    party: "יהדות התורה",
    image: "/leaders/itshak.png",
    color: "#000080",
    values: {
      securityBg: 1,
      economicBg: 2,
      pressure: 3,
      brokenPromises: 2,
      consistency: 4,
      authority: 3,
      communication: 2,
      worldRelations: 1,
      criminal: "ללא",
      lifestyle: "צנוע",
    },
  },
];
